### ISSUE TITLE
`TypeError: 'NoneType' object is not subscriptable`

### ISSUE THREAD

**Issue by OCRenkist** [theopolisme/voice2json#4]
```
~/Downloads/Takeout/Voice$ python voice2json.py ./Calls/ voice.json
Traceback (most recent call last):
  File "voice2json.py", line 158, in <module>
    main()
  File "voice2json.py", line 152, in main
    json = serialize_files_to_json(files)
  File "voice2json.py", line 132, in serialize_files_to_json
    serialized = serialize_general_to_record(f.read())
  File "voice2json.py", line 45, in serialize_general_to_record
    'date': soup.find('abbr', class_='published')['title'],
TypeError: 'NoneType' object is not subscriptable

```

**Comment by thoughtleader** [comment]
Try removing messages titled, "Group Conversation - ....."

Those conversations are structured much differently, the extraction for date is breaking, since instead of one message having one date, Group convos have lots and lots of dates.
